name-template: service-a@$RESOLVED_VERSION # リリースノートのタイトルはタグ名と同じにする
tag-template: service-a@$RESOLVED_VERSION # タイトルとタグ名を同じにする
tag-prefix: service-a@ # tagのprefixを指定
include-paths: # service-aのリリースノートに含めるファイルパスを指定
  - "projects/service_a/"
  - ".github/common.yml"


template: |
  ## Changes

  $CHANGES